# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

# Set the python versions
python:
  - 3.8

# Addons
addons:
  postgresql: "9.4"

# Environment
env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test

# Install pip dependencies
install:
  - pip install -r requirements.txt

stages:
  - name: compile
    if: type = push
  - name: test
    # require the type to be a PR
    if: (branch = develop AND type = push)
  - name: deploy
    # require the type to be push to master
    if: (branch = main AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: compile
      name: "Compile"
        # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - python manage.py test
      deploy:
        provider: heroku
        api_key:
          secure: "p8aZttlVYj4suWedaRAsxHOE0zQT+MBLkvcndiRt5O10QX2qKluarWl5jtuqZj5d8UNdEnJhvUs1Q1kTtrnyT/oSUbeC2ctsJNWLKg173vYIxawvYmCmKFncCWAjAsNdmqYRUm72LF3XDNB2TugRhTi8e7CCJgIHTCZVBP7BhJ3DnOkExwqMjwbLnnxHplITli5HmGXWLilTUsn0lTGhHeA/e3f8zIHMIOR91LIqJOXEyYarEpz+ViLUpavi+ZXXDv+NckDGU4Ytum9JYIl2gt+Aly3HPFEY9PZ1GxE/W9AZLpgYUMbVJfk2rDoKxy0vpCoks/UZwX62btwc7ppKFiLgGr3FuuzmCHkLzlMvdodpjOF1vcv71R/ep++TIsLk3cCMbYu6ttBOcbSKvP3rKuKqUmQjlqhlLe/HyS2RGCGqnQJjgVrSj9vzzfz9Z36ZHJR5akuhEPJW3YKfFnGE/oLQf7Aym0fQITrvtmfCqTT2a+qqZHVi6w4EOVc2+TLMXoHORMtTqQn4Y3+dc5JZaNxPr/8IsW1WaDeafXtlHdiTzvrvWNAydFv5fQDaV+vXFI31l088KvoUnRlU23r3+u89Jby1oHz+PqIYkX6p6pR0Wh/8uTIPNBsnskavGX8MRjgLkfUF8R9LnwHl5LUFJeyjGVcnu/153W+eKo84GPo="
          app: es-scribd-staging
          on:
            repo: UB-ES-2020/scribd
            branch: develop

    - stage: test
      name: "test"
      # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - python manage.py test
      deploy:
        provider: heroku
        api_key:
          secure: "p8aZttlVYj4suWedaRAsxHOE0zQT+MBLkvcndiRt5O10QX2qKluarWl5jtuqZj5d8UNdEnJhvUs1Q1kTtrnyT/oSUbeC2ctsJNWLKg173vYIxawvYmCmKFncCWAjAsNdmqYRUm72LF3XDNB2TugRhTi8e7CCJgIHTCZVBP7BhJ3DnOkExwqMjwbLnnxHplITli5HmGXWLilTUsn0lTGhHeA/e3f8zIHMIOR91LIqJOXEyYarEpz+ViLUpavi+ZXXDv+NckDGU4Ytum9JYIl2gt+Aly3HPFEY9PZ1GxE/W9AZLpgYUMbVJfk2rDoKxy0vpCoks/UZwX62btwc7ppKFiLgGr3FuuzmCHkLzlMvdodpjOF1vcv71R/ep++TIsLk3cCMbYu6ttBOcbSKvP3rKuKqUmQjlqhlLe/HyS2RGCGqnQJjgVrSj9vzzfz9Z36ZHJR5akuhEPJW3YKfFnGE/oLQf7Aym0fQITrvtmfCqTT2a+qqZHVi6w4EOVc2+TLMXoHORMtTqQn4Y3+dc5JZaNxPr/8IsW1WaDeafXtlHdiTzvrvWNAydFv5fQDaV+vXFI31l088KvoUnRlU23r3+u89Jby1oHz+PqIYkX6p6pR0Wh/8uTIPNBsnskavGX8MRjgLkfUF8R9LnwHl5LUFJeyjGVcnu/153W+eKo84GPo="
          app: es-scribd-staging
          on:
            repo: UB-ES-2020/scribd
            branch: develop

    - stage: deploy
      name: "deploy"
      # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - python manage.py test
      deploy:
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: "gDZ5vb4gBfIf4gFd/hDqVOEQ0RRi+g1WnjZtWh9QN0xdu+Lhw2rZH3gNx/XPwRjUb38SrUhQsxNaSNebrSzyvl1AMOkG9woPhLqsoTqHFHwjQ+q+hsvFnoysKFy4u6hoNOx51hLI7oR3/cPHVHV2cOhLkomLT+/Bj3eXbtK8/ybm8HtBMEmHlDUJaJC50SguDrg9ndR9RlHKUM49udY5ZXlop295EW146ZTJWac1pOAnIAUuVQxYA6DcOHJ3Q1zfuyo4Si8MicE47V4eKTQ58BicQmF0yGYqm7iHvrlzB/PLwArbegrOjKrjEgZ4Qx2CBgN5Kp/+3xuF7HlZpA6c8r6SkboWugr++Jcf9BKAa3yF+v+7VLn9z6wGt5GpXuItp/wXxA5xSx6h44SapjzoXdtSgplEC9Z+AQhQFoWr3Tyame0XRWSNtsQ4BZNQGNHb7bbW6H3hV53OrtGltSNR38j2EPhp3nxgwk/iShubpUWCaMqLvLxAG6keg+I3bsMknNf92v/rQQX6uzeeMaR2uq9fX+7bPV69sPrZDM2QraL5I0BMlo7d50aH7bKmYRwXhYk+dyWG/9W4/PBjAuIvgMZ7f+CdKH+cyJZ3JSkrsHPASLcjBxnl+xbxwohW2KkTpcljGkGMZhiwLQkVXLAfYGo6W0KUi+dfuphB6kDNn9s="
          app: es-scribd
          on:
            repo: UB-ES-2020/Scribd
            branch: main
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: "p8aZttlVYj4suWedaRAsxHOE0zQT+MBLkvcndiRt5O10QX2qKluarWl5jtuqZj5d8UNdEnJhvUs1Q1kTtrnyT/oSUbeC2ctsJNWLKg173vYIxawvYmCmKFncCWAjAsNdmqYRUm72LF3XDNB2TugRhTi8e7CCJgIHTCZVBP7BhJ3DnOkExwqMjwbLnnxHplITli5HmGXWLilTUsn0lTGhHeA/e3f8zIHMIOR91LIqJOXEyYarEpz+ViLUpavi+ZXXDv+NckDGU4Ytum9JYIl2gt+Aly3HPFEY9PZ1GxE/W9AZLpgYUMbVJfk2rDoKxy0vpCoks/UZwX62btwc7ppKFiLgGr3FuuzmCHkLzlMvdodpjOF1vcv71R/ep++TIsLk3cCMbYu6ttBOcbSKvP3rKuKqUmQjlqhlLe/HyS2RGCGqnQJjgVrSj9vzzfz9Z36ZHJR5akuhEPJW3YKfFnGE/oLQf7Aym0fQITrvtmfCqTT2a+qqZHVi6w4EOVc2+TLMXoHORMtTqQn4Y3+dc5JZaNxPr/8IsW1WaDeafXtlHdiTzvrvWNAydFv5fQDaV+vXFI31l088KvoUnRlU23r3+u89Jby1oHz+PqIYkX6p6pR0Wh/8uTIPNBsnskavGX8MRjgLkfUF8R9LnwHl5LUFJeyjGVcnu/153W+eKo84GPo="
          app: es-scribd-staging
          on:
            repo: UB-ES-2020/Scribd
            branch: develop

notifications:
  slack:
    secure: uOAWBYKi6S2efmYNA2gDcbAflnCiEElsFHngHrO39Eo/A3avrtliOfJoLt1sl3IQF/KKiyWsGRam3eoWXSA7NMnSRI2x67Pa8U7OYWp8VKSyQmCOQkDnkH9ImPwshx1jVCPfbRHnQzGqBTBonjggf9sAOsLOcc8MgY6UvV7Nto0ZmZ1qaL9oFAtHmd0/yBn1z2xUKanCCs7M1RKv/4Se02rvCTS96f935oej9wBwbRQomZbb/VTpCMl/dZPt+Ej1/UVav0dQfAdioULSQ4Y8VNL/Aeo7oGwcfWjp489uZZ0wKRHZwimsWBq1NAeq5nuPCgNYEvJnJxsDw+SXyV5PWkwWR06QwdfuZdA0jTuNMOBAyHh/bZq/4a4RZuZDIn+PpHRxx+n8tkO2k18sXX1nlmHKd1yP3BLObUjABJ9lSKcdo3pRBBh0VI2juOJZeWNYWwyK1DwPTVx3FRIeg/816y2j+2qNBsARSsGeAMVjIPzE/RJxOJ+Eg1X+97a12dc0VWAWYo43GHseymdveTS+icXx7PUXrHFZvSAoMxRBby3xG/v6hDWCijdWeroOMpbpffj4KsyCgk+9xd5oiHIoZrwC/icwXEnUwrssSO0DJKVK11CLJU3H1iGz/EERMvyMoBEnQKYsy11lJJnOuoLw/YmMOhwWI8/QY8bbr9M6tjc=