language: python
python:
- '3.8.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: 35fde4b6-79ea-4101-8800-5180cf18dec9
  app:
  on:
    repo: UB-ES-2020/Scribd