# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

# Set the python versions
python:
  - 3.8.6

# Addons
addons:
  postgresql: "9.4"

# Environment
env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test

# Install pip dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

stages:
  # CUALQUIER PUSH
  - name: compile
    if: type = pull_request
  - name: test
    # MERGE DE UN PULL REQUEST A DEVELOP
    if: type = push AND branch = develop
  - name: deploy
    # MERGE DE DEVELOP A MAIN
    if: (branch = main AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: compile
      name: "Compile"
      # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - coverage run --source=Scribd manage.py test
      after_success:
        - coveralls

    - stage: test
      name: "test"
      # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - coverage run --source=Scribd manage.py test
      after_success:
        - coveralls
      true:
        repo: UB-ES-2020-A/Scribd
      branches:
        only:
          - master
          - develop
      deploy:
        provider: heroku
        api_key:
          secure: "rcVngq6e7btJeyJyBRTaY4fJ+BbVr5Vf4HibXNBSssYDqjhZV+qb0K4Ms61DuErUUBlMpVv7VsQ8gIKvFHLQQ8Lm9l/weJ0P33E4LQTlIIDGMJ0ELyfag+mWl0Ke9M2+NWwkZVBgmx4S7jDrnOfZzAYVv/gpQqlax3+SckYSApBG+5IBaUXJRMFYg0JJ3le0P2V+bTEewY4eP9PumBwEdX24pCXzm69+7gIci/zthTDJk1QRNbnFcKYcp0x6JTj0UnIbtExvub4m3w6rH8m6aceGaRBrqej9DcbOibuVw6EWmZJG42OJapOh64LgIuMrGCYoQmXfvf1BcYDc8aygEIPaeg78waj1Yd+KvFZgIR2BNk3xPKrzDn4CdcQOBDpb/VgWAul2j4w3uqaXTj2V6vTO7WKcnwF2lktp/fHt5goAE8ZaIVNODVmexNhCOfN+y0OITVPzO0OBVBIHn1NRsszJeOj2jPor+s/vs5rAJkDGm1HNC0m0amDfgXcfAiS4DRzta4ZsPqqRVCI/u6kLJtojJ64SMQzJk7jsZr39uDH95m5Ts6eowwT9GmWA4NmYzQuSJ8YXDp7uJS3KltkWQ01DV9GLgTLEoBP4smKbUrhrocQmNDsdcadkObnY1Vgf+sLTwjotmuckBedRzVCLybfSrD9MObwtoFWkRQS5hRA="
        app:
          master: es-scribd
          develop: es-scribd-staging

    - stage: deploy
      name: "deploy"
      # Create test database
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata fixtures/ebooks.json
      script:
        - coverage run --source=Scribd manage.py test
      after_success:
        - coveralls
      deploy:
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: "rcVngq6e7btJeyJyBRTaY4fJ+BbVr5Vf4HibXNBSssYDqjhZV+qb0K4Ms61DuErUUBlMpVv7VsQ8gIKvFHLQQ8Lm9l/weJ0P33E4LQTlIIDGMJ0ELyfag+mWl0Ke9M2+NWwkZVBgmx4S7jDrnOfZzAYVv/gpQqlax3+SckYSApBG+5IBaUXJRMFYg0JJ3le0P2V+bTEewY4eP9PumBwEdX24pCXzm69+7gIci/zthTDJk1QRNbnFcKYcp0x6JTj0UnIbtExvub4m3w6rH8m6aceGaRBrqej9DcbOibuVw6EWmZJG42OJapOh64LgIuMrGCYoQmXfvf1BcYDc8aygEIPaeg78waj1Yd+KvFZgIR2BNk3xPKrzDn4CdcQOBDpb/VgWAul2j4w3uqaXTj2V6vTO7WKcnwF2lktp/fHt5goAE8ZaIVNODVmexNhCOfN+y0OITVPzO0OBVBIHn1NRsszJeOj2jPor+s/vs5rAJkDGm1HNC0m0amDfgXcfAiS4DRzta4ZsPqqRVCI/u6kLJtojJ64SMQzJk7jsZr39uDH95m5Ts6eowwT9GmWA4NmYzQuSJ8YXDp7uJS3KltkWQ01DV9GLgTLEoBP4smKbUrhrocQmNDsdcadkObnY1Vgf+sLTwjotmuckBedRzVCLybfSrD9MObwtoFWkRQS5hRA="
          app: es-scribd
          on:
            repo: UB-ES-2020-A/Scribd
            branch: main

notifications:
  slack:
    secure: uOAWBYKi6S2efmYNA2gDcbAflnCiEElsFHngHrO39Eo/A3avrtliOfJoLt1sl3IQF/KKiyWsGRam3eoWXSA7NMnSRI2x67Pa8U7OYWp8VKSyQmCOQkDnkH9ImPwshx1jVCPfbRHnQzGqBTBonjggf9sAOsLOcc8MgY6UvV7Nto0ZmZ1qaL9oFAtHmd0/yBn1z2xUKanCCs7M1RKv/4Se02rvCTS96f935oej9wBwbRQomZbb/VTpCMl/dZPt+Ej1/UVav0dQfAdioULSQ4Y8VNL/Aeo7oGwcfWjp489uZZ0wKRHZwimsWBq1NAeq5nuPCgNYEvJnJxsDw+SXyV5PWkwWR06QwdfuZdA0jTuNMOBAyHh/bZq/4a4RZuZDIn+PpHRxx+n8tkO2k18sXX1nlmHKd1yP3BLObUjABJ9lSKcdo3pRBBh0VI2juOJZeWNYWwyK1DwPTVx3FRIeg/816y2j+2qNBsARSsGeAMVjIPzE/RJxOJ+Eg1X+97a12dc0VWAWYo43GHseymdveTS+icXx7PUXrHFZvSAoMxRBby3xG/v6hDWCijdWeroOMpbpffj4KsyCgk+9xd5oiHIoZrwC/icwXEnUwrssSO0DJKVK11CLJU3H1iGz/EERMvyMoBEnQKYsy11lJJnOuoLw/YmMOhwWI8/QY8bbr9M6tjc=