language: python
python:
- 3.8.6
cache: pip
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: 0ZXXKp/AS2yvKyewYRu8EuU8SW9m1AH6xo6hnh0vYIH77rpScswFBx9eU7GW/nb/wdypj6QDqD5dYRMeF40v/OwNfpnbOcc6wZJPr0dP9xMWIrnRYyzHnOkXlNpxBxgm4aAMsiJFJH3t4wJKyKQMFGvKWR94iNxrnPRMrAPLWFxONQU4q7py9zNd69hxEn36N8wPowH15Xxda1mqOFRO/bOvx6hlp9/+SZG5PtRfoCcVl49nc4XysyEWPP/KIyFlk4GBUDOUy7RwSvy8A/vuwiv3BdlO3Vo9gSILWKTZINGyfEUFEyKWUkHt7GQZ3tugSLOc2lLpuA/QaDBcr1jQQmlaLe2ZPsq8s2YCKnoMZsSMTRbhuUB88a3dfLsRSFJuOapNXhXN04Zeh34GW25KwsbOvcKsiMeJ7owgT/JYB8qymfdCsRb1KNLllh9hQ1uDg+Cwgyx+l3Un9ZelumgA+k9BrnZjkmmQ9ghDUM6ykP5mPvuyy2zDSAu0iGiOGpu3ryoQ+CSLWCei/w+2fa9gnpQZirI7IWhJYn+BWP+xt1+Mp0gl+I0qkMPmeEHfCiUI7ciTZyx2oCXbof6L2Da8owesAaLkRx0Lzh6qCgxMncbVYraGwN+To8FkQp3clNb3q1r4sEPK3rBVUPzgu4FzJjCPlQyqADEEqRH7kdaQfv0=
  strategy: git
  app: es-scribd
  on:
    repo: UB-ES-2020/Scribd
