<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-24 16:38

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1.2 on 2020-10-20 17:30

from django.db import migrations, models
>>>>>>> main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Account',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000, unique=True)),
                ('date_registration', models.DateField()),
                ('subscription', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Account',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='SubscribedAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subs', models.DateField()),
                ('free_trial', models.BooleanField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scribd.account')),
            ],
        ),
=======
            name='ebook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('autor', models.CharField(max_length=1024)),
                ('size', models.IntegerField()),
                ('media_type', models.CharField(max_length=16)),
                ('count_downloads', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ebooks',
                'verbose_name_plural': 'Ebooks',
            },
        ),
>>>>>>> main
    ]
