# Generated by Django 3.1.2 on 2020-10-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scribd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookInsertDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='ebook',
            options={'verbose_name': 'Ebook', 'verbose_name_plural': 'Ebooks'},
        ),
        migrations.AddField(
            model_name='ebook',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ebook',
            name='ebook_number',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='featured_photo',
            field=models.ImageField(default='scribd/static/images/', upload_to='scribd/static/images/'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='is_promot',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='count_downloads',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='media_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('epub', 'epub')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ViewedEbooks',
            fields=[
                ('id_vr', models.AutoField(primary_key=True, serialize=False)),
                ('ebook', models.ManyToManyField(through='Scribd.EbookInsertDate', to='Scribd.Ebook')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_stars', models.CharField(choices=[('One star', 1), ('Two stars', 2), ('Three stars', 3), ('Four stars', 4), ('Five stars', 5)], max_length=12)),
                ('comment', models.TextField()),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scribd.ebook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ebookinsertdate',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scribd.ebook'),
        ),
        migrations.AddField(
            model_name='ebookinsertdate',
            name='viewed_ebooks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scribd.viewedebooks'),
        ),
    ]
