# Generated by Django 3.1.2 on 2020-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scribd', '0002_auto_20201026_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ebook',
            name='count_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebook',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ebook',
            name='ebook_number',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='featured_photo',
            field=models.ImageField(default='scribd/static/images/', upload_to='scribd/static/images/'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='is_promot',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='media_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('epub', 'epub')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='ebook',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
