# Generated by Django 3.1.2 on 2020-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scribd', '0003_auto_20201026_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedebooks',
            name='ebook',
            field=models.ManyToManyField(through='Scribd.EbookInsertDate', to='Scribd.Ebook'),
        ),
    ]
